### ISSUE TITLE
Overview of how to set up in Dev?

### ISSUE THREAD

**Issue by madewithsalt** [CodeForPhilly/schoolbudget.phl.io#11]
Hi! I'm Kristi, and I'm one of the mentors with Girl Develop It's Summer of Open Source program!

I was working with one of the other mentors and fellows assigned to contribute to this project, and we had a bit of trouble figuring out all the steps needed to run this site locally.

Could you kindly write up some steps we'd need to run the site locally for development? We can make a more fully-fledged install & deploy guide from your initial write up as part of our contributions with our fellows. :) 

Some of our questions:
- It seems there is no database - how does the site reference and then parse the .csv file from http://webgui.phila.k12.pa.us/offices/o/open-data-initiative ?
- What version of PhP should we have locally? 
- Any other dependencies/libraries should we make sure we have?

Thanks so much for helping to get us started!

**Comment by themightychris** [comment]
I created a branch that doesn't require any PHP backend, it can be loaded as a static website through any web server (or just opened locally if you disable local file restrictions via Safari's develop menu or Chrome's command line option)

https://github.com/CfABrigadePhiladelphia/schoolbudget.phl.io/tree/static-site

**Comment by madewithsalt** [comment]
I think we're rocking it out with the static site now, thanks Chris for setting this up!
